### ISSUE TITLE
0.0.10 crash newest fabric 1.20.4, when brushing supicious sand

### ISSUE THREAD

**Issue by EfficientStinkbug** [RodoFire/mushroooms-mod-source-1.20.1#32]
Description: Ticking entity

java.lang.AbstractMethodError: Receiver class net.minecraft.class_8162 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_239 getHitResult(net.minecraft.class_1309)' of class net.minecraft.class_8162.
	at net.minecraft.class_8162.handler$feh000$mushrooomsmod$amberBlock(class_8162.java:534)
	at net.minecraft.class_8162.method_7852(class_8162.java:107)
	at net.minecraft.class_1799.method_7949(class_1799.java:1044)
	at net.minecraft.class_1309.method_37119(class_1309.java:3066)
	at net.minecraft.class_1309.method_6076(class_1309.java:3058)
	at net.minecraft.class_1309.method_5773(class_1309.java:2408)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_742.method_5773(class_742.java:59)
	at net.minecraft.class_746.method_5773(class_746.java:218)
	at net.minecraft.class_638.method_18646(class_638.java:277)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_638.method_32124(class_638.java:260)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:256)
	at net.minecraft.class_310.method_1574(class_310.java:2011)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by RodoFire** [comment]
I saw what's wrong, I'll fix it
